// Local mock for @graft/nuget-EnergyPriceService (the real client is generated by
// the Graftcode gateway and served from a private project registry).
//
// Graftcode's whole premise is a DIRECT call with no integration layer in between,
// so the mock models that honestly: GetPrice() runs in-process with no network
// round-trip. That makes the "Graftcode" column the fastest in the perf-lab, which
// is the behaviour the real runtime is meant to demonstrate.
//
// NOTE: this is a mock for local UI testing only. The REST and gRPC columns in the
// app still make real HTTP/2 network calls to the running backends.

export const GraftConfig = {
  _host: '',
  set host(value) {
    this._host = value
  },
  get host() {
    return this._host
  },
}

export const EnergyPriceService = {
  // Mirrors electric-company-be: EnergyPriceService.GetPrice() => Random(1, 998).
  async GetPrice() {
    return Math.floor(Math.random() * 997) + 1
  },
}
