// Local mock for @graft/nuget-EnergyPriceService (the real client is generated by
// the Graftcode gateway and served from a private project registry).
//
// This alias exists so the UI can render without the private package. It is
// in-process and is NOT the Graftcode column on GitHub Pages or Azure — those
// use the generated client over the gateway (WSS, or HTTPS/h2 when configured).
// REST and gRPC still make real HTTP/2 calls to the running backends.

export const GraftConfig = {
  _host: '',
  set host(value) {
    this._host = value
  },
  get host() {
    return this._host
  },
}

export const EnergyPriceService = {
  // Mirrors electric-company-be: EnergyPriceService.GetPrice() => Random(1, 998).
  async GetPrice() {
    return Math.floor(Math.random() * 997) + 1
  },

  // Mirrors electric-company-be: EnergyPriceService.GetPriceHistory(count) => double[].
  // Local mock only — no serialization, no network. Do not treat timings from
  // this stub as a production Graftcode measurement.
  async GetPriceHistory(count) {
    const result = new Array(count)
    for (let i = 0; i < count; i++) result[i] = Math.floor(Math.random() * 997) + 1
    return result
  },
}
