<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>AccountService</AssemblyName>
    <RootNamespace>AccountService</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GraftCodeLoggerProject Condition="'$(GraftCodeLoggerProject)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\graftcode-logger\src\netcore\GraftCodeNetcoreLogger\GraftCodeNetcoreLogger.csproj</GraftCodeLoggerProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.4.0" />
    <PackageReference Include="Graftcode.Context" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="OpenTelemetry" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.12.0-beta.2" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(GraftCodeLoggerProject)')">
    <ProjectReference Include="$(GraftCodeLoggerProject)" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('$(GraftCodeLoggerProject)')">
    <PackageReference Include="GraftCodeNetcoreLogger" Version="3.0.5" />
  </ItemGroup>

</Project>
